In [1]:
import vtk
from vtk.util import numpy_support

import numpy as np
import bloscpack as bp

import sys
import os
sys.path.append(os.path.join(os.environ['REPO_DIR'], 'utilities'))
from utilities2015 import *
from annotation_utilities import *

from skimage.measure import mesh_surface_area, marching_cubes, correct_mesh_orientation

from skimage.measure import find_contours

from itertools import izip
import pandas as pd

In [5]:
labels = ['BackG', '5N', '7n', '7N', '12N', 'Pn', 'VLL', 
          '6N', 'Amb', 'R', 'Tz', 'RtTg', 'LRt', 'LC', 'AP', 'sp5']

n_labels = len(labels)

labels_index = dict((j, i) for i, j in enumerate(labels))

labels_from_surround = dict( (l+'_surround', l) for l in labels[1:])

labels_surroundIncluded_list = labels[1:] + [l+'_surround' for l in labels[1:]]
labels_surroundIncluded = set(labels_surroundIncluded_list)

labels_surroundIncluded_index = dict((j, i) for i, j in enumerate(labels_surroundIncluded_list))

# colors = np.random.randint(0, 255, (len(labels_index), 3))
colors = np.loadtxt(os.environ['REPO_DIR'] + '/visualization/100colors.txt')
colors[labels_index['BackG']] = 1.

In [3]:
mesh_rootdir = '/home/yuncong/CSHL_meshes'
if not os.path.exists(mesh_rootdir):
    os.makedirs(mesh_rootdir)

In [6]:
label_polygons = load_label_polygons_if_exists(stack=stack, username='yuncong', force=False)

annotation_on_sections = get_annotation_on_sections(label_polygons=label_polygons, 
                                                    filtered_labels=labels_surroundIncluded)

landmark_range_limits = get_landmark_range_limits(stack=stack, label_polygons=label_polygons, 
                                                  filtered_labels=labels_surroundIncluded)

landmark_zlimits = {l: [(int(z_xy_ratio_downsampled*e1) - atlas_vol_zmin, 
                         int(z_xy_ratio_downsampled*e2) -1 - atlas_vol_zmin) for e1, e2 in ranges] 
                    for l, ranges in landmark_range_limits.iteritems()}

landmark_zlimits_twoSides = {}
for l in range(1, n_labels):
    zlimits = landmark_zlimits[labels[l]]
    if len(zlimits) == 2:
        landmark_zlimits_twoSides[labels[l] + '_L'] = zlimits[0]
        landmark_zlimits_twoSides[labels[l] + '_R'] = zlimits[1]
    elif len(zlimits) == 1:
        landmark_zlimits_twoSides[labels[l]] = zlimits[0]
        
labels_twoSides_name = {name: name if '_' not in name else name[:-2] for name in landmark_zlimits_twoSides.keys()}

labels_twoSides = ['BackG'] + sorted(landmark_zlimits_twoSides.keys())
labels_twoSides_index = dict((j, i) for i, j in enumerate(labels_twoSides))

NameError: name 'load_label_polygons_if_exists' is not defined

In [4]:
# stack = 'MD593'

# for stack in ['MD589', 'MD593']:
for stack in ['MD594']:
    
    volume_xmin, volume_xmax, volume_ymin, volume_ymax, volume_zmin, volume_zmax = \
#         np.loadtxt('/home/yuncong/CSHL_volumes/volume_' + stack + '_annotation_limits.txt')
        np.loadtxt('/home/yuncong/CSHL_volumes/volume_' + stack + '_annotation_smoothed_limits.txt')
        
    _, voxel_size_xy, section_zdistance = np.loadtxt('/home/yuncong/CSHL_volumes/volume_' + stack + '_annotation_resolution.txt')
    
#     annotation_zlimits = pd.read_hdf('/home/yuncong/Brain/database/'+stack+'_label_polygons.h5', 'zlimits').to_dict()
    
    mesh_dir = create_if_not_exists(os.path.join(mesh_rootdir, stack))

#     data_matrix_int = bp.unpack_ndarray_file('/home/yuncong/CSHL_volumes/volume_' + stack + '_annotation.bp')
    data_matrix_int = bp.unpack_ndarray_file('/home/yuncong/CSHL_volumes/volume_' + stack + '_annotation_smoothed.bp')
    ydim, xdim, zdim = data_matrix_int.shape

    data_matrix = data_matrix_int.astype(np.uint8)
    print xdim, ydim, zdim

    first_bs_sec, last_bs_sec = section_range_lookup[stack]
    midsection = (first_bs_sec + last_bs_sec)/2

    for l in labels[1:]:

        print l

        vol_pair = (data_matrix == label_dict[l]).astype(np.float)
        
        vol_list = []
        name_list = []
        
        if l not in annotation_zlimits:
            continue
        
        if len(annotation_zlimits[l]) == 1:
            vol_list.append(vol_pair)
            name_list.append(l)
            
        elif len(annotation_zlimits[l]) == 2:
            vol = vol_pair.copy()

            lo, up = np.array(annotation_zlimits[l][0])*section_zdistance - volume_zmin
            print lo, up
            vol[..., :int(np.floor(lo))] = 0
            vol[..., int(np.ceil(up)):] = 0
            vol_list.append(vol)
            name_list.append(l+'_L')

            vol = vol_pair.copy()

            lo, up = np.array(annotation_zlimits[l][1])*section_zdistance - volume_zmin
            print lo, up            
            vol[..., :int(np.floor(lo))] = 0
            vol[..., int(np.ceil(up)):] = 0
            vol_list.append(vol)
            name_list.append(l+'_R')

        for vol, name in izip(vol_list, name_list):
                
            vs, faces = marching_cubes(vol, .5)
            fs = correct_mesh_orientation(vol, vs, faces)

            print vs.shape, fs.shape

            polydata = vtk.vtkPolyData()

            points = vtk.vtkPoints()
            for pt_ind, (x,y,z) in enumerate(vs):
                points.InsertPoint(pt_ind, x, y, z)

            cells = vtk.vtkCellArray()
            for ia, ib, ic in fs:
                cells.InsertNextCell(3)
                cells.InsertCellPoint(ia)
                cells.InsertCellPoint(ib)
                cells.InsertCellPoint(ic)

            polydata.SetPoints(points)
            polydata.SetPolys(cells)
            polydata.SetVerts(cells)

            for simplify_iter in range(3):

                deci = vtk.vtkQuadricDecimation()
                if simplify_iter == 0:
                    deci.SetInputData(polydata)
                else:
                    deci.SetInputData(smoother.GetOutput())
                deci.SetTargetReduction(0.8)
                deci.Update()

                smoother = vtk.vtkWindowedSincPolyDataFilter()
        #         smoother.NormalizeCoordinatesOn()
                smoother.SetPassBand(.1)
                smoother.SetNumberOfIterations(20)
                smoother.SetInputData(deci.GetOutput())
                smoother.Update()

                print deci.GetOutput().GetNumberOfPoints()

            stlWriter = vtk.vtkSTLWriter()

            stlWriter.SetFileName(mesh_dir + "/%(stack)s_%(name)s.stl" % {'stack': stack, 'name': name})

            stlWriter.SetInputData(smoother.GetOutput())
            stlWriter.Write()            

SyntaxError: invalid syntax (<ipython-input-4-6f3df7ad242a>, line 6)

In [66]:
colors = np.random.randint(0, 255, (len(polydata_list), 3)) / 255.

In [70]:
np.savetxt('colors.txt', colors)

In [7]:
colors = np.loadtxt('colors.txt')

In [5]:
polydata_list = {}

for stack in ['MD593']:
    for l in labels[1:]:
        fn_L = '/home/yuncong/CSHL_meshes/%(stack)s/%(stack)s_%(label)s_L.stl' % {'stack': stack, 'label': l}
        
        if os.path.exists(fn_L):
            reader = vtk.vtkSTLReader()
            reader.SetFileName(fn_L)
            reader.Update()

            polydata_list[l] = []
            polydata_list[l].append(reader.GetOutput())

            fn_R = '/home/yuncong/CSHL_meshes/%(stack)s/%(stack)s_%(label)s_R.stl' % {'stack': stack, 'label': l}
            reader = vtk.vtkSTLReader()
            reader.SetFileName(fn_R)
            reader.Update()

            polydata_list[l].append(reader.GetOutput())
            
        else:
            fn = '/home/yuncong/CSHL_meshes/%(stack)s/%(stack)s_%(label)s.stl' % {'stack': stack, 'label': l}
            
            reader = vtk.vtkSTLReader()
            reader.SetFileName(fn)
            reader.Update()
            
            polydata_list[l] = [reader.GetOutput()]

In [8]:
ren1 = vtk.vtkRenderer()
renWin = vtk.vtkRenderWindow()
renWin.AddRenderer(ren1)
iren = vtk.vtkRenderWindowInteractor()
iren.SetRenderWindow(renWin)

camera = vtk.vtkCamera()

# camera.SetViewUp(-1, -1, 0)
# camera.SetPosition(-20, -30, 10)
# camera.SetFocalPoint(1, -1, -1)

# saggital
# camera.SetViewUp(-1, 0, 0)
# camera.SetPosition(0, 0, 2)
# camera.SetFocalPoint(0, 0, 1)

# horizontal
# camera.SetViewUp(0, 0, -1)
# camera.SetPosition(-2, 0, 0)
# camera.SetFocalPoint(1, 0, 0)

# # coronal
# camera.SetViewUp(-1, 0, 0)
# camera.SetPosition(0, -3, 0)
# camera.SetFocalPoint(0, 1, 0)

for i, (l, polydatas) in enumerate(polydata_list.iteritems()):

    for polydata in polydatas:
    
        m = vtk.vtkPolyDataMapper()
        m.SetInputData(polydata)
    #     m.SetInputData(reader.GetOutput())
    #     m.SetInputConnection(reader.GetOutputPort())

        a = vtk.vtkActor()
        a.SetMapper(m)
#         a.GetProperty().SetRepresentationToWireframe()
        a.GetProperty().SetColor(colors[i])

        ren1.AddActor(a)
        ren1.SetActiveCamera(camera)
        ren1.ResetCamera()

renWin.Render()
iren.Start()

In [112]:
from collections import defaultdict

In [127]:
vertices_allLandmarks = defaultdict(list)
for i, (l, polydatas) in enumerate(polydata_list.iteritems()):
    for polydata in polydatas:
        try:
            vertices = numpy_support.vtk_to_numpy(polydata.GetPoints().GetData())
            vertices_allLandmarks[l].append(vertices)
        except Exception as e:
            print l
            print e.message

RtTg
'NoneType' object has no attribute 'GetData'
SuVe
'NoneType' object has no attribute 'GetData'


/usr/local/lib/python2.7/dist-packages/ipykernel/__main__.py:9: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6


In [131]:
centroid_allLandmarks = dict([(l, [vs.mean(axis=0) for vs in vs_list]) 
                              for l, vs_list in vertices_allLandmarks.iteritems()])

In [132]:
centroid_allLandmarks

{'12N': [array([ 167.35136414,  544.12615967,  234.80662537], dtype=float32)],
 '5N': [array([ 129.01428223,  218.81552124,   50.86375046], dtype=float32),
  array([ 151.58226013,  230.10757446,  419.84210205], dtype=float32)],
 '6N': [array([ 153.94859314,  297.47265625,  185.3600769 ], dtype=float32),
  array([ 151.12915039,  299.28390503,  284.74005127], dtype=float32)],
 '7N': [array([ 256.95004272,  351.48596191,   55.20360565], dtype=float32),
  array([ 284.63525391,  351.98156738,  385.42202759], dtype=float32)],
 '7n': [array([ 171.3986969 ,  278.80847168,   93.85617065], dtype=float32),
  array([ 198.30714417,  279.4826355 ,  374.16506958], dtype=float32)],
 'AP': [array([ 110.82328796,  542.5501709 ,  239.81834412], dtype=float32)],
 'Amb': [array([ 211.80039978,  454.78070068,   44.19460297], dtype=float32),
  array([ 250.92416382,  454.76837158,  397.52661133], dtype=float32)],
 'Gr': [array([ 121.49416351,  604.61016846,  201.12780762], dtype=float32),
  array([ 135.192031