In [1]:
%reload_ext autoreload
%autoreload 2

import os
import sys
sys.path.append(os.path.join(os.environ['REPO_DIR'], 'utilities'))
from visualization_utilities import *
from metadata import *
from utilities2015 import *

Setting environment for Precision WorkStation


In [2]:
from pandas import *

# Check structure annotations

In [3]:
structures_df = DataManager.load_annotation_v4(stack='MD661', by_human=True, 
timestamp='latest', suffix='structures')

aws s3 cp --recursive "s3://mousebrainatlas-data/CSHL_labelings_v3/MD661" "/home/yuncong/CSHL_labelings_v3/MD661" --exclude "*" --include "*structures*"
0
latest timestamp:  02062018184326


In [37]:
def get_edit_transform(structures_df):
    for struct_id, structure_info in structures_df.iterrows():
        if structure_info['volume'] is not None:
            vol = bp.unpack_ndarray_str(structure_info['volume'])
            name_s = compose_label(structure_info['name'], side=structure_info['side'])
            print name_s, [ed['type'] for ed in structure_info['edits']]

            global_tf_from_wholebrain_to_wholebrain_volResol = np.eye(4)
            local_tf_from_wholebrain_to_wholebrain_volResol = np.eye(4)
            composed_tf_from_wholebrain_to_wholebrain_volResol = np.eye(4)
            for edit in structure_info['edits']:
                edit_tf_from_wholebrain_to_wholebrain_volRes = consolidate(edit['transform'])
                if edit['type'].startswith('global'): #  global_rotate3d or global_shift3d
                    global_tf_from_wholebrain_to_wholebrain_volResol = \
                    np.dot(edit_tf_from_wholebrain_to_wholebrain_volRes, global_tf_from_wholebrain_to_wholebrain_volResol)
                elif edit['type'].startswith('prob'):
                    local_tf_from_wholebrain_to_wholebrain_volResol = \
                    np.dot(edit_tf_from_wholebrain_to_wholebrain_volRes, local_tf_from_wholebrain_to_wholebrain_volResol)                    
                    
                composed_tf_from_wholebrain_to_wholebrain_volResol = \
                np.dot(edit_tf_from_wholebrain_to_wholebrain_volRes, composed_tf_from_wholebrain_to_wholebrain_volResol)

            print global_tf_from_wholebrain_to_wholebrain_volResol.reshape((4,4))[:3]
            print local_tf_from_wholebrain_to_wholebrain_volResol.reshape((4,4))[:3]
            print composed_tf_from_wholebrain_to_wholebrain_volResol.reshape((4,4))[:3]

In [38]:
get_edit_transform(structures_df)

Sp5C_L ['global_shift3d', 'global_rotate3d', 'global_rotate3d', 'global_shift3d', 'global_shift3d', 'prob_shift3d']
[[   0.96810387    0.25054921    0.         -112.26988376]
 [  -0.25054921    0.96810387    0.          218.69344179]
 [   0.            0.            1.          -16.56      ]]
[[  1.           0.           0.          32.71111111]
 [  0.           1.           0.         -18.4       ]
 [  0.           0.           1.           0.        ]]
[[   0.96810387    0.25054921    0.          -79.55877265]
 [  -0.25054921    0.96810387    0.          200.29344179]
 [   0.            0.            1.          -16.56      ]]
SNR_L ['global_shift3d', 'global_rotate3d', 'global_rotate3d', 'global_shift3d', 'global_shift3d']
[[   0.96810387    0.25054921    0.         -112.26988376]
 [  -0.25054921    0.96810387    0.          218.69344179]
 [   0.            0.            1.          -16.56      ]]
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]]
[[   0.96810387    0.250549

# Newer version

In [4]:
stack = 'MD589'

In [176]:
labeling_dir = '/home/yuncong/CSHL_labelings_v3/' + stack

In [177]:
annotations = {}

for fp in sorted(os.listdir(labeling_dir)):
    data = load_hdf_v2(os.path.join(labeling_dir, fp))
    print fp
    for ind, row in data.iterrows():
        print row['name'], row['section']
        annotations[(row['name'], row['section'])] = row    

CHATM3_annotation_contours_04162018144225.hdf
Pn 160
CHATM3_annotation_contours_04162018144658.hdf
Pn 160
7N 160
IC 160
SNC 160
5N 160
SNR 160
SC 160
CHATM3_annotation_contours_04162018144850.hdf
7n 160
5N 160
SNC 160
SC 160
Pn 160
Amb 160
LRt 160
SNR 160
7N 160
IC 160
CHATM3_annotation_contours_04162018145757.hdf
SNC 163
SNC 160
IC 163
7n 160
5N 164
SNR 160
SC 163
SC 160
7N 160
IC 160
Pn 166
LRt 160
5N 160
Pn 160
SNR 163
Amb 160
CHATM3_annotation_contours_04162018150333.hdf
LRt 160
IC 163
SC 163
5N 164
Pn 166
SNC 176
SNR 160
7N 160
LRt 163
5N 160
SNC 163
SNC 160
SNR 163
7n 160
SC 160
Pn 160
Amb 160
SNC 171
SNR 176
SNR 171
7N 170
IC 160
CHATM3_annotation_contours_04162018152327.hdf
RtTg 192
7n 192
SC 163
7N 170
SNR 176
SC 184
SNR 163
Tz 184
Tz 205
SC 200
IC 184
Pn 166
6N 204
RtTg 207
RtTg 184
Pn 160
SNC 176
SNR 182
LC 175
RtTg 204
Pn 207
RMC 192
RMC 184
Tz 192
RMC 207
RMC 200
IC 207
LRt 160
SC 160
SNR 171
6N 207
7n 200
LRt 163
5N 160
7n 160
IC 200
SNC 171
IC 160
Tz 207
6N 205
5N 164
SC

In [178]:
sorted(annotations.keys())

[('10N', 211),
 ('10N', 235),
 ('10N', 247),
 ('12N', 211),
 ('12N', 227),
 ('12N', 235),
 ('12N', 247),
 ('5N', 160),
 ('5N', 164),
 ('6N', 204),
 ('6N', 205),
 ('6N', 207),
 ('7N', 160),
 ('7N', 170),
 ('7n', 160),
 ('7n', 192),
 ('7n', 200),
 ('AP', 227),
 ('AP', 235),
 ('Amb', 160),
 ('IC', 160),
 ('IC', 163),
 ('IC', 184),
 ('IC', 200),
 ('IC', 207),
 ('IC', 219),
 ('IC', 227),
 ('LC', 175),
 ('LRt', 160),
 ('LRt', 163),
 ('Pn', 160),
 ('Pn', 166),
 ('Pn', 184),
 ('Pn', 192),
 ('Pn', 207),
 ('RMC', 184),
 ('RMC', 192),
 ('RMC', 200),
 ('RMC', 207),
 ('RMC', 235),
 ('RMC', 247),
 ('RtTg', 184),
 ('RtTg', 192),
 ('RtTg', 204),
 ('RtTg', 207),
 ('RtTg', 211),
 ('RtTg', 227),
 ('SC', 160),
 ('SC', 163),
 ('SC', 184),
 ('SC', 200),
 ('SC', 207),
 ('SC', 219),
 ('SC', 227),
 ('SNC', 160),
 ('SNC', 163),
 ('SNC', 171),
 ('SNC', 176),
 ('SNR', 160),
 ('SNR', 163),
 ('SNR', 171),
 ('SNR', 176),
 ('SNR', 182),
 ('Tz', 184),
 ('Tz', 192),
 ('Tz', 205),
 ('Tz', 207)]

In [179]:
merged_annotations_table = DataFrame(annotations.values())

In [180]:
merged_annotations_table

class  creator  \
61417973919587   contour  yuncong   
165498910605087  contour  yuncong   
110473719026558  contour  yuncong   
102790288330653  contour  yuncong   
108860727905611  contour  yuncong   
131633584750329  contour  yuncong   
217866353503758  contour  yuncong   
146476015747094  contour  yuncong   
126673529461145  contour  yuncong   
65942681262602   contour  yuncong   
92010441865970   contour  yuncong   
193478745432178  contour  yuncong   
19224556955380   contour  yuncong   
139228538863710  contour  yuncong   
257545148886987  contour  yuncong   
106159580668830  contour  yuncong   
191227155178395  contour  yuncong   
82935703639810   contour  yuncong   
101105623500811  contour  yuncong   
71804313132620   contour  yuncong   
137746592275401  contour  yuncong   
22145578028625   contour  yuncong   
225036892786054  contour  yuncong   
172039536449513  contour  yuncong   
190012648470873  contour  yuncong   
118078330761052  contour  yuncong   
279234224597201  contour  yuncong   
136849910734993  contour  yuncong   
155600714878127  contour  yuncong   
118141688879573  contour  yuncong   
...                  ...      ...   
56675330531695   contour  yuncong   
171678345729631  contour  yuncong   
186241270864853  contour  yuncong   
228564174641203  contour  yuncong   
175689311675128  contour  yuncong   
32622169502262   contour  yuncong   
1574135016703    contour  yuncong   
177794470581010  contour  yuncong   
243845345800769  contour  yuncong   
201873184737238  contour  yuncong   
25170032822165   contour  yuncong   
249688371806136  contour  yuncong   
72892179232617   contour  yuncong   
35369942739671   contour  yuncong   
208396518302891  contour  yuncong   
108604012128914  contour  yuncong   
267157701410975  contour  yuncong   
278317122053111  contour  yuncong   
121121780988994  contour  yuncong   
40087874423371   contour  yuncong   
679030166790     contour  yuncong   
183524020131991  contour  yuncong   
41974728783487   contour  yuncong   
258190930164209  contour  yuncong   
115137821918288  contour  yuncong   
267094528604537  contour  yuncong   
113458660685089  contour  yuncong   
251517374402717  contour  yuncong   
140476437520067  contour  yuncong   
211443647724471  contour  yuncong   

                                                             edits  \
61417973919587   [{u'username': u'yuncong', u'timestamp': u'041...   
165498910605087  [{u'username': u'yuncong', u'timestamp': u'041...   
110473719026558  [{u'username': u'yuncong', u'timestamp': u'041...   
102790288330653  [{u'username': u'yuncong', u'timestamp': u'041...   
108860727905611  [{u'username': u'yuncong', u'timestamp': u'041...   
131633584750329  [{u'username': u'yuncong', u'timestamp': u'041...   
217866353503758  [{u'username': u'yuncong', u'timestamp': u'041...   
146476015747094  [{u'username': u'yuncong', u'timestamp': u'041...   
126673529461145  [{u'username': u'yuncong', u'timestamp': u'041...   
65942681262602   [{u'username': u'yuncong', u'timestamp': u'041...   
92010441865970   [{u'username': u'yuncong', u'timestamp': u'041...   
193478745432178  [{u'username': u'yuncong', u'timestamp': u'041...   
19224556955380   [{u'username': u'yuncong', u'timestamp': u'041...   
139228538863710  [{u'username': u'yuncong', u'timestamp': u'041...   
257545148886987  [{u'username': u'yuncong', u'timestamp': u'041...   
106159580668830  [{u'username': u'yuncong', u'timestamp': u'041...   
191227155178395  [{u'username': u'yuncong', u'timestamp': u'041...   
82935703639810   [{u'username': u'yuncong', u'timestamp': u'041...   
101105623500811  [{u'username': u'yuncong', u'timestamp': u'041...   
71804313132620   [{u'username': u'yuncong', u'timestamp': u'041...   
137746592275401  [{u'username': u'yuncong', u'timestamp': u'041...   
22145578028625   [{u'username': u'yuncong', u'timestamp': u'041...   
225036892786054  [{u'username': u'yuncong', u'timestamp': u'041...   
172039536449513  [{u'username': u'yuncong', 

In [181]:
fp = DataManager.get_annotation_filepath(stack=stack, by_human=True, suffix='contours', timestamp='now')
save_hdf_v2(merged_annotations_table, fp)
upload_to_s3(fp)

aws s3 cp "/home/yuncong/CSHL_labelings_v3/CHATM3/CHATM3_annotation_contours_04172018132221.hdf" "s3://mousebrainatlas-data/CSHL_labelings_v3/CHATM3/CHATM3_annotation_contours_04172018132221.hdf"
0


In [183]:
contours_df, timestamp = DataManager.load_annotation_v4(stack=stack, by_human=True, timestamp='latest', 
                                                        suffix='contours', return_timestamp=True)

aws s3 cp --recursive "s3://mousebrainatlas-data/CSHL_labelings_v3/CHATM2" "/home/yuncong/CSHL_labelings_v3/CHATM2" --exclude "*" --include "*contours*"
0
latest timestamp:  04172018132213


In [184]:
contours_df

class  creator  \
187424345944670  contour  yuncong   
131542146410241  contour  yuncong   
258771944424632  contour  yuncong   
206211808342086  contour  yuncong   
43110298657518   contour  yuncong   
36601380358710   contour  yuncong   
276240472044097  contour  yuncong   
34196477312018   contour  yuncong   
3350986096957    contour  yuncong   
242216048696653  contour  yuncong   
214416038922443  contour  yuncong   
144924019828513  contour  yuncong   
207182581285708  contour  yuncong   
202658134005267  contour  yuncong   
35581476564596   contour  yuncong   
124747056837657  contour  yuncong   
188443124660425  contour  yuncong   
13793625407255   contour  yuncong   
234241147094946  contour  yuncong   
35680010608953   contour  yuncong   
10765692813728   contour  yuncong   
20409678226758   contour  yuncong   
118680639568805  contour  yuncong   
222571583386296  contour  yuncong   
31172547874695   contour  yuncong   
213328760695323  contour  yuncong   
115501198103905  contour  yuncong   

                                                             edits  \
187424345944670  [{u'username': u'yuncong', u'timestamp': u'041...   
131542146410241  [{u'username': u'yuncong', u'timestamp': u'041...   
258771944424632  [{u'username': u'yuncong', u'timestamp': u'041...   
206211808342086  [{u'username': u'yuncong', u'timestamp': u'041...   
43110298657518   [{u'username': u'yuncong', u'timestamp': u'041...   
36601380358710   [{u'username': u'yuncong', u'timestamp': u'041...   
276240472044097  [{u'username': u'yuncong', u'timestamp': u'041...   
34196477312018   [{u'username': u'yuncong', u'timestamp': u'041...   
3350986096957    [{u'username': u'yuncong', u'timestamp': u'041...   
242216048696653  [{u'username': u'yuncong', u'timestamp': u'041...   
214416038922443  [{u'username': u'yuncong', u'timestamp': u'041...   
144924019828513  [{u'username': u'yuncong', u'timestamp': u'041...   
207182581285708  [{u'username': u'yuncong', u'timestamp': u'041...   
202658134005267  [{u'username': u'yuncong', u'timestamp': u'041...   
35581476564596   [{u'username': u'yuncong', u'timestamp': u'041...   
124747056837657  [{u'username': u'yuncong', u'timestamp': u'041...   
188443124660425  [{u'username': u'yuncong', u'timestamp': u'041...   
13793625407255   [{u'username': u'yuncong', u'timestamp': u'041...   
234241147094946  [{u'username': u'yuncong', u'timestamp': u'041...   
35680010608953   [{u'username': u'yuncong', u'timestamp': u'041...   
10765692813728   [{u'username': u'yuncong', u'timestamp': u'041...   
20409678226758   [{u'username': u'yuncong', u'timestamp': u'041...   
118680639568805  [{u'username': u'yuncong', u'timestamp': u'041...   
222571583386296  [{u'username': u'yuncong', u'timestamp': u'041...   
31172547874695   [{u'username': u'yuncong', u'timestamp': u'041...   
213328760695323  [{u'username': u'yuncong', u'timestamp': u'041...   
115501198103905  [{u'username': u'yuncong', u'timestamp': u'041...   

                                     filename               id  \
187424345944670  CHATM2_slide88_2018_02_13-S2  187424345944670   
131542146410241  CHATM2_slide92_2018_02_13-S2  131542146410241   
258771944424632  CHATM2_slide92_2018_02_13-S2  258771944424632   
206211808342086  CHATM2_slide80_2018_02_14-S2  206211808342086   
43110298657518   CHATM2_slide88_2018_02_13-S2   43110298657518   
36601380358710   CHATM2_slide88_2018_02_13-S2   36601380358710   
276240472044097  CHATM2_slide54_2018_01_22-S2  276240472044097   
34196477312018   CHATM2_slide92_2018_02_13-S2   34196477312018   
3350986096957    CHATM2_slide54_2018_01_22-S2    3350986096957   
242216048696653  CHATM2_slide80_2018_02_14-S2  242216048696653   
214416038922443  CHATM2_slide54_2018_01_22-S2  214416038922443   
144924019828513  CHATM2_slide84_2018_02_14-S3  144924019828513   
207182581285708  CHATM2_slide80_2018_02_14-S2  207182581285708   
202658134005267  CHATM2_slide84_2018_02_14-S3  202658134005267   
35581476564596   CHATM2_slide84

# New version

In [5]:
contours_df, timestamp = DataManager.load_annotation_v4(stack='MD589', by_human=True, timestamp='latest', 
                                                        suffix='contours', return_timestamp=True)

aws s3 cp --recursive "s3://mousebrainatlas-data/CSHL_labelings_v3/MD589" "/home/yuncong/CSHL_labelings_v3/MD589" --exclude "*" --include "*contours*"
0
latest timestamp:  04192018111821


In [6]:
contours_df

class  creator  \
100079545430812  contour  yuncong   
10032954325690   contour  yuncong   
10042629543436   contour  yuncong   
100499768892293  contour  yuncong   
100567129513785  contour  yuncong   
100571878935576  contour  yuncong   
100716602659441  contour  yuncong   
10076160352035   contour  yuncong   
100898193708403  contour  yuncong   
100909285842903  contour  yuncong   
100935086975740  contour  yuncong   
101025151639472  contour  yuncong   
101213755924449  contour  yuncong   
101302221740433  contour   nicole   
101616954239178  contour  yuncong   
101641350083689  contour  yuncong   
101675697977740  contour  yuncong   
101704946895326  contour  yuncong   
101740238278869  contour  yuncong   
10177309636610   contour  yuncong   
101817708942539  contour  yuncong   
101837004223912  contour  yuncong   
102058363052463  contour  yuncong   
102169597017613  contour  yuncong   
102235852763413  contour  yuncong   
102365174139323  contour  yuncong   
102423392703025  contour  yuncong   
102443241166748  contour  yuncong   
102543021427528  contour  yuncong   
10259052829000   contour  yuncong   
...                  ...      ...   
96469709260532   contour  yuncong   
96471438034736   contour  yuncong   
96979573160981   contour  yuncong   
97198047830394   contour  yuncong   
97359165471924   contour  yuncong   
97640065703607   contour  yuncong   
97733609302330   contour  yuncong   
97765104314279   contour  yuncong   
97786029796820   contour  yuncong   
97946665746222   contour  yuncong   
97970613194909   contour  yuncong   
98147521435710   contour  yuncong   
98305726626672   contour  yuncong   
98400631722540   contour  yuncong   
98441744796279   contour  yuncong   
98508394678598   contour  yuncong   
98601479970553   contour  yuncong   
98604277329075   contour  yuncong   
98814819192065   contour  yuncong   
98873190427480   contour  yuncong   
98890624912723   contour  yuncong   
99095624841107   contour  yuncong   
99120482617093   contour  yuncong   
99201557887028   contour  yuncong   
99446275791470   contour  yuncong   
99600816899241   contour  yuncong   
9980871449160    contour  yuncong   
99870215486391   contour  yuncong   
99911770143889   contour  yuncong   
99991412762735   contour  yuncong   

                                                             edits  \
100079545430812  [{u'username': u'yuncong', u'timestamp': u'091...   
10032954325690   [{u'username': u'yuncong', u'timestamp': u'091...   
10042629543436   [{u'username': u'yuncong', u'timestamp': u'091...   
100499768892293  [{u'username': u'yuncong', u'timestamp': u'091...   
100567129513785  [{u'username': u'yuncong', u'timestamp': u'091...   
100571878935576  [{u'username': u'yuncong', u'timestamp': u'091...   
100716602659441  [{u'username': u'yuncong', u'timestamp': u'091...   
10076160352035   [{u'username': u'yuncong', u'timestamp': u'091...   
100898193708403  [{u'username': u'yuncong', u'timestamp': u'091...   
100909285842903  [{u'username': u'yuncong', u'timestamp': u'091...   
100935086975740  [{u'username': u'yuncong', u'timestamp': u'091...   
101025151639472  [{u'username': u'yuncong', u'timestamp': u'091...   
101213755924449  [{u'username': u'yuncong', u'timestamp': u'091...   
101302221740433  [{u'username': u'nicole', u'timestamp': u'0419...   
101616954239178  [{u'username': u'yuncong', u'timestamp': u'041...   
101641350083689  [{u'username': u'yuncong', u'timestamp': u'091...   
101675697977740  [{u'username': u'yuncong', u'timestamp': u'091...   
101704946895326  [{u'username': u'yuncong', u'timestamp': u'091...   
101740238278869  [{u'username': u'yuncong', u'timestamp': u'091...   
10177309636610   [{u'username': u'yuncong', u'timestamp': u'091...   
101817708942539  [{u'username': u'yuncong', u'timestamp': u'091...   
101837004223912  [{u'username': u'yuncong', u'timestamp': u'091...   
102058363052463  [{u'username': u'yuncong', u'timestamp': u'091...   
102169597017613  [{u'username': u'yuncong', 

In [9]:
contours_df = contours_df[(contours_df['filename'] != 'Placeholder') & (contours_df['name'] == '7N')]

In [6]:
contours_df['side'][contours_df['name'] == '12N'] = 'S'

In [7]:
contours_df[(contours_df['type'] == 'confirmed') & (contours_df['name'] == '12N')]

Empty DataFrame
Columns: [class, creator, edits, filename, id, label_position, name, orientation, parent_structure, resolution, section, side, side_manually_assigned, time_created, type, vertices]
Index: []

In [24]:
sagittal_contours_df_fp = DataManager.get_annotation_filepath(stack='MD658', by_human=True, suffix='contours', 
                                                              timestamp='now')
save_hdf_v2(contours_df, sagittal_contours_df_fp)
upload_to_s3(sagittal_contours_df_fp)

/usr/local/lib/python2.7/dist-packages/pandas/core/generic.py:939: PerformanceWarning: 
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->mixed-integer,key->block0_values] [items->['class', 'creator', 'downsample', 'edits', 'filename', 'id', 'label_position', 'name', 'orientation', 'parent_structure', 'section', 'side', 'side_manually_assigned', 'time_created', 'type', 'vertices']]

  return pytables.to_hdf(path_or_buf, key, self, **kwargs)


aws s3 cp "/home/yuncong/CSHL_labelings_v3/MD658/MD658_annotation_contours_01082018162524.hdf" "s3://mousebrainatlas-data/CSHL_labelings_v3/MD658/MD658_annotation_contours_01082018162524.hdf"


# Old version

In [1]:
stack = 'MD635'

In [6]:
fp = '/home/yuncong/CSHL_labelings_v3/%(stack)s/%(stack)s_annotation_v3.h5' % {'stack': stack}
download_from_s3(fp)
contours = read_hdf(fp)

rm -rf "/home/yuncong/CSHL_labelings_v3/MD635/MD635_annotation_v3.h5" && mkdir -p "/home/yuncong/CSHL_labelings_v3/MD635"
aws s3 cp "s3://mousebrainatlas-data/CSHL_labelings_v3/MD635/MD635_annotation_v3.h5" "/home/yuncong/CSHL_labelings_v3/MD635/MD635_annotation_v3.h5"


In [12]:
contours[(contours['name'] == '7N') & (contours['section'] == 158)]

creator downsample  \
102627349379154  yuncong          1   
106833387670490  yuncong          1   

                                                             edits  \
102627349379154  [{u'username': u'yuncong', u'timestamp': u'122...   
106833387670490  [{u'username': u'yuncong', u'timestamp': u'122...   

                                                   filename flags  \
102627349379154  MD635-F53-2016.05.19-05.14.50_MD635_2_0158     1   
106833387670490  MD635-F53-2016.05.19-05.14.50_MD635_2_0158     1   

                              id                  label_position name  \
102627349379154  102627349379154  [25175.1667763, 12351.1854336]   7N   
106833387670490  106833387670490  [25175.1667763, 12351.1854336]   7N   

                orientation parent_structure section side  \
102627349379154    sagittal               []     158    L   
106833387670490    sagittal               []     158    L   

                side_manually_assigned    time_created  \
102627349379154                  False  12262016143425   
106833387670490                  False  12262016141652   

                                                          vertices  
102627349379154  [[24780.2371365, 12783.8648579], [24620.295638...  
106833387670490  [[24780.2371365, 12783.8648579], [24620.295638...

In [7]:
from annotation_utilities import *

In [8]:
contours = contours[(contours['orientation'] == 'sagittal') & (contours['downsample'] == 1)]
contours = convert_annotation_v3_original_to_aligned_cropped(contours, stack=stack)

In [10]:
grouped = contours.groupby('section')

In [15]:
for sec, group in grouped:
    for contour_id, contour in group.iterrows():
        print contour_id
    print '\n'

24041485827291


178638821776884


225468065711699


82753828715844


108639196063443
240450955921646


139995532033938
276274803125745


123201065869455
50599366457376


128891739813762
280008487571593
74734208874016


137576545852286
139884971202912
44979814970993


198648392198851
252434421302035
53849871852705


215403441631652
272974593078035
32236200064177


165920538830976
243256546173591
58906621711441


175994136617351
258516032496448
45531577507434


187863059163195
193809479990018
245020993386827


124244720326548
28990358901640
6039163938366


13783358246531
269642137367206
93951936437221


170927976283983
250086639456848
65686469868581


12994163947428
131268714517286
180619860209674
3348124243740


140881450963675
171250512966690
277597751075951
90654685894305


124892661563969
202987135024252
207964402507211
50422758984114
63049897456070


236059505041962
259084303736308
69129898116566
86007295995378
95926547893398


111731759580942
135434889301284
265153680649971
273505