In [1]:
%reload_ext autoreload
%autoreload 2

import os
import sys
sys.path.append(os.path.join(os.environ['REPO_DIR'], 'utilities'))
from visualization_utilities import *
from metadata import *
from utilities2015 import *

Setting environment for Local Macbook Pro


In [2]:
from pandas import *

# Check structure annotations

In [4]:
structures_df = DataManager.load_annotation_v4(stack='CHATM3', by_human=True, 
timestamp='latest', suffix='structures')

aws s3 cp --recursive "s3://mousebrainatlas-data/CSHL_labelings_v3/CHATM3" "/home/yuncong/CSHL_labelings_v3/CHATM3" --exclude "*" --include "*structures*"
0
latest timestamp:  05102018102201


In [21]:
for sid, structure in structures_df.iterrows():
    print structure['name'], structure['side'], bp.unpack_ndarray_str(structure['volume']).shape

Pn L (129, 143, 145)
SNR L (252, 157, 199)
3N R (45, 81, 37)
Sp5O L (156, 338, 69)
10N L (54, 189, 84)
LC R (98, 109, 39)
SNC R (175, 98, 110)
VLL R (292, 176, 119)
PBG R (117, 66, 74)
SNC L (170, 96, 122)
Tz R (63, 133, 77)
4N R (35, 29, 27)
PBG L (127, 66, 43)
VLL L (285, 192, 119)
AP S (46, 91, 54)
Sp5C L (242, 301, 152)
RMC L (95, 109, 109)
LC L (103, 105, 45)
DC R (106, 176, 184)
Amb L (36, 87, 18)
LRt R (89, 199, 105)
3N L (62, 79, 37)
6N R (38, 36, 33)
Sp5I L (156, 269, 80)
10N R (81, 183, 67)
SNR R (251, 154, 199)
DC L (106, 176, 184)
VCA L (138, 162, 94)
VCP L (164, 109, 94)
IC S (311, 208, 438)
5N R (119, 100, 74)
6N L (38, 36, 33)
Tz L (55, 138, 77)
7N R (79, 119, 152)
VCP R (173, 109, 74)
12N S (86, 168, 108)
7N L (97, 129, 118)
7n L (155, 106, 188)
4N L (35, 29, 27)
RMC R (95, 109, 109)
SC S (305, 319, 462)
VCA R (149, 162, 85)
Sp5I R (166, 270, 80)
5N L (119, 100, 74)
RtTg S (165, 178, 233)
Pn R (129, 143, 145)
Amb R (37, 89, 18)
LRt L (89, 199, 105)
Sp5C R (210, 325, 152

In [22]:
def get_edit_transform(structures_df):
    for struct_id, structure_info in structures_df.iterrows():
        if structure_info['volume'] is not None:
            vol = bp.unpack_ndarray_str(structure_info['volume'])
            name_s = compose_label(structure_info['name'], side=structure_info['side'])
            print name_s, [ed['type'] for ed in structure_info['edits']]

            global_tf_from_wholebrain_to_wholebrain_volResol = np.eye(4)
            local_tf_from_wholebrain_to_wholebrain_volResol = np.eye(4)
            composed_tf_from_wholebrain_to_wholebrain_volResol = np.eye(4)
            for edit in structure_info['edits']:
                edit_tf_from_wholebrain_to_wholebrain_volRes = consolidate(edit['transform'])
                if edit['type'].startswith('global'): #  global_rotate3d or global_shift3d
                    global_tf_from_wholebrain_to_wholebrain_volResol = \
                    np.dot(edit_tf_from_wholebrain_to_wholebrain_volRes, global_tf_from_wholebrain_to_wholebrain_volResol)
                elif edit['type'].startswith('prob'):
                    local_tf_from_wholebrain_to_wholebrain_volResol = \
                    np.dot(edit_tf_from_wholebrain_to_wholebrain_volRes, local_tf_from_wholebrain_to_wholebrain_volResol)                    
                    
                composed_tf_from_wholebrain_to_wholebrain_volResol = \
                np.dot(edit_tf_from_wholebrain_to_wholebrain_volRes, composed_tf_from_wholebrain_to_wholebrain_volResol)

            print global_tf_from_wholebrain_to_wholebrain_volResol.reshape((4,4))[:3]
            print local_tf_from_wholebrain_to_wholebrain_volResol.reshape((4,4))[:3]
            print composed_tf_from_wholebrain_to_wholebrain_volResol.reshape((4,4))[:3]

In [5]:
get_edit_transform(structures_df)

SNR_R ['idle', 'global_shift3d', 'global_shift3d', 'global_shift3d']
[[  1.           0.           0.          42.810525  ]
 [  0.           1.           0.         -10.15347555]
 [  0.           0.           1.          18.29485642]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[1.00000000e+00 0.00000000e+00 0.00000000e+00 1.17958358e+03]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 5.97622082e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 4.30182702e+02]]
SNR_L ['idle', 'global_shift3d', 'global_shift3d', 'global_shift3d']
[[  1.           0.           0.          42.810525  ]
 [  0.           1.           0.         -10.15347555]
 [  0.           0.           1.          18.29485642]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[1.00000000e+00 0.00000000e+00 0.00000000e+00 1.17958358e+03]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 5.97622082e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 4.30182702e+02]]


# 2-D Contours

In [6]:
stack = 'MD589'

In [7]:
labeling_dir = '/home/yuncong/CSHL_labelings_v3/' + stack

In [8]:
data = load_hdf_v2(os.path.join(labeling_dir, 'MD589_annotation_contours_04192018111821.hdf'))

In [5]:
annotations = {}

for fp in sorted(os.listdir(labeling_dir)):
    if 'contour' in fp:
        data = load_hdf_v2(os.path.join(labeling_dir, fp))
        print fp
        for ind, row in data.iterrows():
            print row['name'], row['section']
            annotations[(row['name'], row['section'])] = row    

MD585_annotation_contours_04192018113554.hdf
SC 249
IC 180
DC 130
10N 216
IO 230
SC 195
IC 232
5N 141
SolIM 175
7n 156
SC 172
VCP 337
Bar 180
IC 174
IO 201
Pn 193
7n 296
RMC 255
Sp5C 151
SC 251
Tz 235
Pn 205
Sp5I 105
SNC 295
SNR 314
8n 103
VCA 100
7n 232
7n 188
8n 101
SC 218
PBG 138
IC 212
RtTg 205
IC 291
7n 167
8n 102
PBG 125
5N 153
DC 321
Tz 246
Sp5I 111
5N 151
RtTg 212
RtTg 235
SNC 145
7n 154
VCA 87
RtTg 207
VLL 143
Pn 185
LPB 142
6N 228
LC 259
VCP 105
SNC 141
SC 308
7N 272
RMC 191
SC 292
RtTg 189
Sp5C 154
Sol 170
RtTg 195
SC 317
Sp5I 301
RtTg 245
SC 273
VCP 104
7n 270
IC 184
Pn 236
Pn 202
Sp5C 114
Tz 255
12N 202
7n 288
LC 258
SNC 273
7n 170
SC 164
Sp5I 296
12N 196
7N 258
VCP 102
DC 88
7N 177
5N 290
SC 290
LRt 284
Sp5C 117
6N 189
IC 166
Sp5C 113
IO 241
DC 291
SC 227
IC 239
VCA 83
SNR 306
SpVe 149
SNC 275
5N 286
Sp5I 309
Pn 201
Sp5C 153
SNR 304
SNC 268
Pn 195
VCP 92
SNR 300
Tz 206
SNC 308
Sp5C 147
7n 245
Tz 198
Tz 186
LVe 141
8n 314
SNC 277
7N 268
RtTg 215
VLL 131
AP 196
VCP 322
VLL 

DC 90
IC 210
SC 148
Amb 269
SNR 157
Amb 149
VCA 110
RMC 207
SNR 277
VCA 335
Pn 206
Sp5I 104
DC 305
RtTg 184
Sp5C 123
IC 287
10N 204
VCA 104
Sp5O 310
10N 194
IC 271
5N 147
SuVe 138
SNC 298
SC 207
6N 186
Sp5C 141
7N 171
7n 257
IC 183
RtTg 180
IC 178
SNC 263
Pr5DM 119
SC 166
AP 191
SNC 304
7n 139
Sp5O 280
Sp5I 126
IC 234
Sp5I 124
7N 266
LPB 143
SNC 168
SC 158
7N 180
Tz 230
7n 251
IC 249
IC 167
RtTg 203
SC 222
IC 303
VCA 324
IC 298
SNC 162
Sp5C 129
SuVe 141
SNR 318
RMC 239
7N 264
IC 247
SC 190
VLL 137
8n 305
SNR 305
Pn 241
Pn 186
VCA 95
DC 119
3N 234
IC 200
SC 139
12N 192
10N 191
Pr5DM 309
SNR 175
12N 198
4N 205
VCA 342
Tz 253
VCA 101
IC 289
VCA 340
VCP 96
IC 268
LRt 141
SC 316
IO 200
SNR 271
SC 233
Sp5O 117
SC 240
SNR 275
DC 110
SC 246
SC 163
VCP 315
SC 268
VCP 94
PBG 129
7N 263
DC 124
12N 203
LC 260
SC 257
VLL 135
SNC 283
DC 304
7N 174
7n 150
8n 315
VCP 317
SC 286
Sp5C 139
Sp5O 301
SC 266
Tz 238
IO 199
VLL 304
Tz 188
SC 313
RMC 274
Tz 233
Sp5I 306
5N 155
PBG 133
Pr5DM 306
3N 228
VCP 334


Sp5I 129
SNC 273
IC 281
Sp5C 166
Sp5C 282
Sp5I 122
IC 162
SC 143
VCA 326
Pn 204
RtTg 219
Sp5C 155
4N 232
RMC 239
RtTg 259
12N 189
SC 192
Sp5C 109
AP 202
DC 91
Pn 276
SC 286
LRt 284
10N 206
SNC 286
RMC 203
VCP 331
Tz 237
Sp5O 117
SC 262
SNR 147
SNC 271
12N 212
Sp5I 296
IC 163
SNR 184
IC 180
SC 283
SNR 268
DC 330
Sol 164
Sp5I 288
7N 169
7n 171
8n 107
VCA 323
Sp5C 130
IC 251
8n 109
DC 293
DC 313
SNR 320
Sp5C 153
IC 237
SC 185
RMC 192
RtTg 250
Pn 261
8n 307
SNR 133
5N 141
10N 185
Sp5O 106
6N 225
SNC 307
DC 134
IC 152
Sp5I 103
SNR 311
7n 282
7n 239
RtTg 242
PBG 126
SNR 178
AP 191
DC 311
SC 277
5N 145
Pn 215
5N 275
SC 158
Pn 268
12N 211
7N 162
IC 137
VLL 301
7n 249
Pn 241
VLL 145
7N 170
Pn 242
5N 152
12N 188
SC 242
RtTg 177
SNC 290
5N 151
DC 305
IC 211
SNR 307
7N 175
IO 196
10N 180
VLL 303
IC 146
SC 238
3N 226
SC 164
VLL 310
RtTg 253
Sp5I 308
DC 104
SNR 282
AP 197
7n 176
SC 296
Sp5O 310
10N 188
Pn 209
Sp5O 113
RMC 256
Pn 184
RtTg 245
SNR 149
Cb 270
RMC 208
SNR 163
IC 256
7N 283
5N 282
IC 149

SC 279
7n 135
PBG 137
IO 195
Pr5DM 114
Sp5O 301
SC 178
SC 303
LC 261
7n 165
Sp5O 121
RtTg 249
Sp5C 110
7N 162
Sp5I 129
SC 235
DC 290
10N 190
IC 159
SC 143
IC 174
SC 207
SC 270
RtTg 214
7n 174
SNC 269
DC 114
Tz 205
5N 286
SC 246
SC 300
SNR 170
DC 306
SC 141
SC 198
SC 167
SC 235
RtTg 194
SC 316
SC 206
Pr5DM 117
7n 294
SNC 283
Pn 185
8n 103
VLL 149
SC 314
8n 307
VCP 343
SC 214
7n 272
Tz 237
SNC 270
VCA 107
SNR 169
IC 230
SC 218
SC 232
LRt 147
Sp5C 139
LC 259
IO 202
SC 275
VCA 337
SC 147
DC 117
SC 234
7n 139
SC 179
MVePC 170
VCP 318
7N 167
SC 212
8n 102
RMC 247
5N 140
IC 300
SC 252
7N 155
SNR 293
SC 168
IC 183
IC 202
SC 200
RtTg 216
SNC 148
SC 230
VCA 91
SC 315
Pn 194
VCP 97
7N 261
SC 281
Sp5O 128
PBG 129
SC 153
SC 141
LPB 144
7n 167
RtTg 242
SC 189
LC 169
SC 206
IC 197
SC 307
PBG 314
12N 194
DC 324
7N 255
SC 270
SC 149
Sp5C 134
SC 249
SC 160
SC 240
RtTg 227
SC 254
IC 185
12N 187
Pn 230
IC 219
SC 277
8n 113
IC 146
IO 229
7n 296
7N 252
SC 238
IC 286
Amb 275
DC 135
IC 282
SC 220
SC 266
7n 24

SC 155
SC 150
SC 250
SNC 290
SC 283
MVeMC 170
VLL 155
IO 231
10N 219
10N 208
12N 193
SC 254
SC 254
SC 280
10N 215
IC 243
VCP 94
Cu 170
Pn 259
SC 257
SC 285
SC 256
Pn 170
5N 141
SC 309
SpVe 170
SC 178
SNR 180
DC 301
SC 214
SNR 306
Pr5DM 311
6N 223
SNR 137
SC 314
IC 156
RMC 202
SNR 143
4N 211
SC 150
RMC 243
SC 229
8n 116
SC 167
VLL 301
SNR 173
Pn 277
SC 219
SC 279
SC 270
SC 313
Tz 202
SC 187
VCP 321
SC 144
VCA 327
IC 167
SC 226
Sp5I 305
SNR 183
SNC 279
VCA 109
SC 304
Tz 195
SC 186
Sp5C 133
SC 237
IC 268
10N 222
RMC 237
4N 213
Sp5O 117
SC 171
SC 162
3N 210
VCP 324
IC 294
SC 280
SC 255
Sp5C 296
SC 261
4N 231
IC 291
7n 250
SNC 144
SC 221
PBG 323
Sp5C 151
SC 177
RMC 258
LVe 141
SC 227
Pn 270
7n 263
DC 320
10N 188
SC 202
SNC 303
SC 158
Sp5O 127
IC 295
Sp5C 125
SC 161
8n 121
SC 191
SC 137
7N 148
10N 181
VCP 344
7n 151
SC 148
SNC 278
SC 173
SC 206
10N 214
5N 147
SC 207
SC 213
VLL 153
Sol 160
SC 148
10N 191
SC 243
SC 211
Pn 261
7n 283
Sp5I 121
DC 333
AP 193
Tz 194
7n 141
SC 279
7n 288
SC 287
VLL

Pn 234
AP 194
DC 324
10N 193
PBG 131
7N 157
RtTg 231
IC 287
SNR 175
SC 207
SNR 155
VCA 334
Sp5I 301
Sp5O 109
SpVe 167
12N 200
7n 178
Sp5C 147
SNC 160
IC 185
7n 188
Sp5O 129
3N 217
RtTg 179
Pn 179
VCA 330
SNR 272
RtTg 205
8n 108
AP 203
7N 170
IO 197
RMC 252
IO 202
3N 230
7N 146
RMC 258
SNC 168
Sp5O 314
Pn 184
Pn 188
RtTg 244
LVe 137
RtTg 204
12N 185
7N 263
SNC 305
VLL 292
SNC 300
RMC 261
Tz 181
Sp5C 116
RtTg 237
IC 280
RtTg 201
VLL 148
Sp5C 282
SNC 150
Pn 176
Sp5O 107
Pn 243
VCA 350
3N 216
SC 239
7n 176
7n 290
SC 263
IO 201
IC 232
SNR 154
8n 117
RtTg 226
RtTg 243
VCA 337
SNR 302
IC 292
Sp5O 115
Amb 272
VCP 328
SC 228
7n 248
IC 275
7N 150
7n 149
Tz 246
SNC 293
Pr5DM 316
7n 264
5N 293
IC 249
SC 184
DC 302
Pn 252
SC 195
3N 227
IC 217
8n 103
DC 130
VCP 107
7N 152
DC 133
RtTg 191
SNR 167
7N 179
IC 252
IC 295
7N 294
DC 101
7N 141
Pn 215
7n 168
SNR 285
10N 213
IC 222
RtTg 254
AP 204
DC 108
SC 310
7n 294
Sp5C 114
Pn 192
SNR 278
5N 144
7n 243
Tz 201
Tz 194
SNC 157
RMC 245
7n 266
SNR 180
VLL 291


RMC 197
IO 226
5N 279
SuVe 142
SNR 291
SC 171
Sp5I 124
RtTg 248
SC 191
12N 204
PBG 135
SNR 146
12N 195
12N 217
7n 262
7n 270
Sol 164
SC 222
SC 151
LRt 160
7N 179
Sp5C 142
MVeMC 160
Pr5DM 115
DC 314
5N 150
10N 190
Tz 181
SNC 285
IC 267
6N 195
SC 317
SC 228
IC 174
SNC 163
Pn 266
DC 318
SC 303
IC 303
Pn 263
RMC 192
SNR 290
SNR 294
SC 141
SC 201
Pn 205
SNR 137
IC 290
SC 189
Pr5DM 319
VCP 328
IC 250
SNC 150
DC 291
SNC 300
RMC 191
IC 251
RMC 185
IC 289
RtTg 184
SNC 277
RtTg 194
SNR 150
RtTg 198
IC 145
Sp5O 307
Sp5C 143
SuVe 137
AP 204
LRt 170
SNR 145
Sp5I 116
Pn 179
Pn 254
3N 234
SC 229
SC 254
RtTg 251
SC 147
LRt 283
SC 230
LC 260
RMC 193
IC 198
SNC 307
VLL 298
SNR 302
7N 277
VCP 324
Sp5C 154
DC 115
SNR 316
RMC 257
8n 115
LC 172
LVe 136
SNC 297
SC 248
5N 294
7N 171
SNR 133
7N 254
7n 181
5N 281
DC 129
DC 338
DC 321
10N 215
IC 222
SuVe 141
VCP 339
7N 252
Tz 193
4N 208
Pn 193
SC 250
7N 289
SC 311
DC 330
SC 204
IC 170
SNR 174
IC 179
Sp5O 306
10N 221
7N 153
RMC 204
12N 199
SNR 162
6N 197
RtTg 225

SNR 173
AP 200
SuVe 137
Sp5C 108
10N 192
10N 214
RtTg 201
IC 259
RtTg 258
7n 169
SC 210
RMC 203
SC 225
DC 324
DC 95
SC 189
VCA 83
Sp5I 114
RtTg 221
RtTg 246
Pn 279
Pn 207
Pn 194
DC 320
4N 211
Sp5I 292
RMC 187
RtTg 225
RMC 267
4N 206
SNC 169
IC 220
RtTg 183
Pn 231
7n 271
SNC 154
7N 160
MVeMC 157
7N 154
Tz 229
SNR 310
SC 227
DC 132
SNR 181
5N 157
Tz 244
SC 202
Sp5C 114
IC 271
DC 126
VCP 309
RtTg 210
7n 148
SC 156
12N 189
Sp5O 314
VLL 148
SC 306
7N 168
RtTg 243
IC 313
DC 108
5N 146
DC 102
Cb 351
IO 243
Pn 251
SC 205
3N 232
Sp5I 309
Pn 257
VCA 106
5N 148
SNC 155
VCA 101
IC 138
IC 144
Pr5VL 305
7n 228
DC 295
RtTg 237
SC 209
10N 186
5N 294
IC 197
SC 201
VCA 95
Sp5C 131
IC 181
IC 161
SuVe 142
SC 173
IC 173
IC 187
Sp5C 150
3N 230
SNR 307
10N 184
7N 273
Sp5O 305
IC 309
SC 234
SC 304
Tz 185
SC 308
IC 193
VCA 108
SC 296
RMC 245
Pn 263
10N 210
Sp5O 274
IO 244
SNC 306
6N 187
DC 326
7n 163
7n 232
7n 226
AP 197
RtTg 207
SNC 302
IC 302
Tz 205
7n 149
DC 312
7N 264
SNC 262
Pn 188
IC 278
SC 266
7n 279
LR

SNC 271
RMC 237
SNR 156
SC 155
LRt 280
SNC 168
AP 203
SC 161
SC 196
SNR 294
7N 161
LPB 140
LPB 145
LC 171
SC 258
VCA 100
RMC 195
7N 266
IC 294
Amb 269
Sp5C 142
IC 298
7n 274
Pn 253
IO 203
8n 307
7n 297
AP 204
SpVe 170
10N 195
AP 201
4N 208
VCA 331
SNR 298
Pn 236
DC 92
7n 145
7n 263
Sp5O 117
6N 223
IC 211
Sp5C 113
SC 230
VCA 333
SNR 183
VCA 344
7n 167
SC 171
IC 248
SC 232
DC 315
4N 229
DC 322
VLL 300
Sp5C 135
VCA 90
7N 144
IC 198
8n 107
7N 151
MD585_annotation_contours_05212018141450.hdf
RMC 204
Tz 197
VLL 286
LRt 276
IC 154
RMC 234
SC 137
VLL 136
IO 231
7N 276
7N 160
SNR 140
7n 272
Sp5O 306
SC 277
LRt 278
Sp5I 312
SNC 296
SC 305
6N 227
Pn 232
SC 226
DC 304
VCP 344
Pn 260
7n 244
DC 313
RtTg 232
Sp5C 127
Pn 258
Sp5O 109
SNC 286
6N 186
Cu 160
Pn 262
IC 297
IC 133
VCP 327
IC 247
IC 274
RtTg 253
DC 99
VCA 327
LC 255
7n 280
IC 263
SNC 175
SNR 272
7n 277
VLL 291
RMC 267
RMC 213
12N 218
SuVe 138
Pn 250
VCP 91
DC 89
3N 218
Sp5C 132
SNR 144
SNC 156
12N 215
LRt 152
IC 186
RMC 244
IC 250
Tz 251
7n

7n 249
Pn 230
RtTg 222
7N 267
SNR 143
SC 193
DC 93
3N 234
10N 183
10N 215
Pr5DM 116
RMC 243
VLL 304
7N 265
VCA 326
SNC 145
RtTg 219
7n 173
Tz 256
SNR 317
Tz 203
IO 199
IC 143
Pn 197
Pn 242
SC 209
Sp5C 134
7N 156
SNR 297
VCA 92
SNR 159
10N 193
IC 160
VCA 100
SNR 298
7N 278
10N 191
Tz 235
5N 276
SC 224
IC 249
7N 292
VCP 312
VLL 151
SC 150
Sp5I 292
IC 131
7n 168
DC 107
SC 260
Pn 243
7N 159
VCA 347
SC 245
SNR 152
7N 151
PBG 308
IC 168
IC 205
7N 258
SNC 267
7n 247
SNC 278
Sp5I 102
SNR 320
SNR 157
RtTg 195
SNC 266
4N 236
Tz 201
SNR 155
7n 139
RtTg 248
VCA 99
PBG 324
7N 263
LRt 165
SC 153
Pr5DM 316
7n 175
VLL 145
10N 207
7N 270
IC 239
RtTg 214
8n 102
Pn 279
RMC 201
VCA 348
Pr5DM 305
8n 121
IC 189
Sp5I 308
IC 144
DC 105
RMC 203
10N 175
Tz 206
SC 174
Tz 257
IC 313
IC 257
SNR 291
RtTg 259
SC 250
7n 232
7n 174
SC 179
5N 136
Pn 263
RtTg 184
Tz 252
SNR 284
DC 128
SC 246
SNR 267
5N 144
3N 220
7N 171
RMC 259
SNR 181
5N 275
IO 238
DC 131
VCP 99
4N 237
SNC 168
DC 104
SC 308
LPB 134
Sp5C 121
RtTg 233
IC

IC 256
7N 278
Amb 269
12N 199
Pn 247
7n 245
RtTg 242
Pn 174
IC 262
VCP 102
SNR 175
RMC 242
7N 176
RMC 199
Tz 181
7N 287
12N 217
DC 328
RtTg 233
SNC 292
Sp5C 120
VCP 336
7N 182
Sp5I 119
IC 295
IC 134
Sp5I 104
4N 229
IC 235
SC 166
SNR 267
Tz 198
RtTg 181
SC 194
VCP 341
Tz 195
IO 236
SNR 179
5N 287
SNR 305
SC 174
SNC 306
7N 144
7N 168
SNR 260
SC 185
RtTg 223
IC 288
10N 220
7n 135
Pn 171
SC 193
7n 266
LRt 276
Pr5DM 313
IC 178
LC 175
SNR 168
Pr5VL 305
SNC 169
LC 261
LRt 278
SC 180
IC 259
10N 179
SNR 273
7n 226
4N 234
SC 178
SC 262
RtTg 248
7n 171
7n 280
IC 206
LRt 141
10N 205
DC 134
SNC 154
RtTg 244
IC 271
7N 264
VCP 97
SC 291
7n 144
7n 230
Pn 236
RMC 186
DC 337
Tz 191
7n 231
Pn 259
Sp5C 124
SC 275
IC 248
RMC 212
Sp5C 121
Gr 175
7n 274
RMC 238
RtTg 254
Tz 230
IC 218
SC 225
SuVe 138
SC 278
7n 146
SC 222
RMC 273
8n 127
RtTg 238
SNR 269
VCP 313
SNR 152
Pn 242
IO 245
VLL 146
Sp5I 128
RMC 233
VCP 343
DC 98
VCA 88
VLL 300
IC 197
IC 210
LVe 137
SNR 263
SNC 141
IC 263
MVeMC 170
SC 161
8n 125
12N 21

SC 138
Sp5C 140
IC 249
IC 190
Sp5O 311
7n 232
IC 157
LC 175
3N 214
Sp5I 116
7n 243
VCA 349
Sp5I 274
Sp5O 125
IC 191
7n 277
Pn 242
DC 121
VCP 100
DC 102
VCA 90
SC 166
12N 208
7n 186
VLL 142
DC 96
Amb 272
VCA 323
5N 281
10N 180
SC 205
SNR 267
Pn 170
IC 253
SC 151
SNC 286
PBG 322
VCA 347
PBG 135
SC 251
SC 201
SNC 266
DC 106
SNR 144
6N 193
Tz 240
RMC 209
SNR 261
Amb 275
12N 201
4N 234
7n 155
IC 219
RtTg 181
SNC 163
6N 230
7n 140
SC 234
SC 289
7n 163
IC 196
DC 318
VLL 302
RtTg 245
RtTg 192
VCP 325
SNR 140
AP 202
SNR 274
7n 246
5N 158
6N 227
LC 172
7n 151
RMC 267
SNR 270
7n 227
7n 145
SNR 136
VCP 337
3N 227
SpVe 160
SC 263
Pn 181
DC 319
Amb 276
RtTg 180
Cb 210
Cb 300
IC 204
Tz 186
8n 117
SC 273
SNC 164
LRt 170
LC 258
Sp5C 113
5N 284
SNR 295
RtTg 216
5N 272
VCP 323
Sp5C 288
DC 125
IC 189
LC 173
SC 269
DC 329
SNC 166
SNR 290
SNC 285
SNR 316
Pn 255
PBG 310
Sp5O 292
Sp5I 111
SNR 277
PBG 130
RtTg 177
4N 208
8n 309
VCA 332
VCA 106
SC 275
RtTg 236
Sp5O 314
Pn 259
Pr5DM 310
VCP 321
5N 279
7N 265
Tz 

RMC 262
IC 192
VLL 292
VCA 91
5N 294
4N 207
SNC 148
SNR 148
10N 216
Sp5I 103
SC 172
Pn 186
SNR 293
VCA 327
7n 293
7n 160
IC 283
Sp5C 121
7n 143
DC 334
7N 148
DC 95
IC 150
7N 176
RMC 208
RMC 269
12N 195
Sol 167
IC 172
IC 208
SNC 287
7N 283
Tz 239
7N 294
Sp5I 128
SC 231
Amb 149
Pn 205
IC 215
SNR 142
IC 159
Sp5C 267
Pn 182
IC 290
Amb 271
Pr5DM 121
VLL 149
12N 206
SC 175
5N 136
Sp5I 306
X 125
SC 288
10N 204
SC 198
RtTg 225
SNR 127
7n 275
Sp5O 117
IC 232
VLL 152
Pr5DM 113
6N 196
SNC 149
Sp5I 106
IO 242
IC 145
12N 200
RMC 247
7N 284
MD585_annotation_contours_05212018152305.hdf
SNR 148
SuVe 137
DC 329
Tz 256
SNR 145
Sp5O 119
5N 157
5N 136
Pr5DM 316
IC 276
Tz 188
Sp5C 280
RMC 191
AP 198
8n 119
Sp5I 122
SNC 273
DC 323
DC 89
Sp5C 143
DC 120
Pn 171
7n 289
SNR 136
RMC 254
RMC 261
SNR 296
IC 244
DC 112
DC 126
7N 142
RMC 251
RMC 238
SNC 166
Sp5C 145
8n 308
Pn 274
IC 306
7n 166
Sp5O 125
SNR 157
7n 135
RMC 253
7N 278
IC 288
Sp5I 125
VCP 329
SC 282
IC 189
SC 304
SC 232
SNR 285
VCP 95
Sp5C 114
SNC 308
7

RMC 241
Pn 179
LPB 135
LVe 138
LC 171
8n 114
SC 220
7N 290
10N 206
IC 175
7n 232
MVeMC 160
SuVe 138
RtTg 188
Sp5I 306
SC 142
SNC 169
IO 199
7N 259
SNR 126
IC 267
Tz 183
SC 153
SNC 288
7N 143
IC 227
SC 281
5N 153
RtTg 210
SNR 159
SNC 266
SC 136
SNR 153
Sp5C 120
RMC 252
SC 247
VCP 316
12N 191
7n 270
VCA 325
SNR 295
12N 219
8n 306
Sp5C 136
5N 280
RMC 270
LC 256
AP 196
Sp5C 121
LC 167
LC 254
VCP 315
7n 280
Sp5O 109
6N 227
SC 264
SC 315
IC 254
7N 273
SC 148
IC 152
Sp5O 306
RtTg 182
IO 241
Sp5I 311
12N 197
SNC 279
Pr5DM 308
SNC 300
DC 95
Pn 207
7n 167
IC 301
VLL 154
SC 202
IC 282
5N 284
VLL 287
7N 145
7n 170
RtTg 234
3N 213
7n 276
AP 191
SNC 155
Pr5DM 313
RMC 240
7N 147
LC 172
Sp5O 301
Amb 155
RtTg 220
DC 338
RMC 207
RMC 272
VLL 149
LRt 284
SNR 322
SC 143
DC 133
RtTg 252
RtTg 205
7n 182
DC 318
SNR 313
12N 210
IC 166
7n 268
Sp5O 310
Sp5O 314
Tz 189
SC 279
SC 233
SNC 289
LRt 281
7n 272
8n 100
Sp5C 124
IC 150
RtTg 240
7n 241
8n 110
12N 212
Tz 232
3N 234
LPB 137
7n 145
SC 162
SNC 294
IC 231
10N 

IC 274
RtTg 210
RtTg 217
RMC 212
SC 144
7N 280
SC 220
10N 215
RtTg 239
12N 203
SpVe 149
IC 214
7n 162
7N 289
SNR 165
4N 234
RtTg 213
10N 217
SNR 309
MVeMC 160
7N 165
Pn 260
Sp5O 305
SNC 167
RtTg 182
SC 281
12N 199
SC 157
SuVe 138
SC 173
SNR 174
SC 154
IC 148
IC 206
Pr5DM 117
IC 253
PBG 138
IC 245
VLL 137
PBG 128
VCP 100
7N 168
Sp5I 111
IC 262
SNC 165
Pn 197
DC 326
6N 191
SC 187
Sp5C 135
DC 135
SNR 317
RMC 268
SNR 161
SNC 300
Tz 186
8n 124
DC 313
SNC 148
LPB 135
SNR 179
VCA 342
Pn 272
IC 308
Pn 278
RtTg 250
SC 278
SC 260
SC 172
RMC 259
RtTg 197
8n 108
7n 240
RtTg 232
10N 176
SNR 291
7n 267
Pr5DM 315
SC 200
VCP 327
7N 269
DC 338
12N 187
Sp5I 114
SNR 145
RMC 245
Sp5O 274
7n 238
VCP 315
VLL 293
RtTg 191
VCA 328
Sp5O 117
VCA 327
5N 284
DC 94
DC 133
SC 285
IC 311
SuVe 143
VCA 108
12N 208
RtTg 186
Cb 352
Sp5C 145
3N 219
Sp5I 136
7n 157
Pr5DM 319
8n 312
IC 184
DC 115
Pn 246
Tz 242
PBG 310
3N 214
5N 293
SNR 283
7N 172
DC 324
Pn 183
RtTg 192
SNC 158
Pn 187
IC 197
7n 253
7n 160
SNC 270
SNR 260
Am

Tz 193
Pr5DM 305
Tz 184
7n 233
IC 298
RMC 201
SNR 314
SNR 306
LPB 144
5N 143
VCP 101
RtTg 214
IC 138
IO 240
SC 219
MVePC 167
DC 130
IO 236
VLL 127
7n 232
DC 310
SNR 292
DC 304
LPB 134
7N 177
SC 213
12N 218
SC 313
SNR 162
10N 195
VLL 290
Sp5C 127
RtTg 193
Sp5O 301
RtTg 238
SNC 159
Tz 195
IC 264
5N 291
SNC 272
3N 232
DC 100
3N 233
IC 256
Sp5I 102
3N 234
RtTg 176
IC 280
SNR 323
12N 207
Sol 160
IC 244
4N 231
SNR 264
SNC 296
6N 230
Sp5O 292
Amb 273
SC 244
8n 106
7N 286
Pn 253
SC 300
Sp5I 296
SNC 154
LC 175
Sp5C 292
DC 119
7n 256
Sp5O 309
8n 306
RMC 188
Sp5I 108
Tz 238
IC 189
IC 131
VCA 105
Pn 165
DC 315
Tz 237
SNR 304
RMC 191
VCA 85
IC 196
IC 172
3N 221
Pn 205
IC 212
4N 235
7N 161
SC 264
IC 239
IC 166
7N 279
8n 119
SC 185
7n 167
RtTg 179
Sp5C 146
RtTg 226
SC 283
5N 288
Cb 180
DC 330
4N 213
RtTg 256
8n 307
12N 200
SNR 146
Pn 269
Pn 172
VLL 148
Tz 197
RtTg 189
DC 331
7n 179
Cb 300
7N 157
RMC 237
RtTg 259
SNC 303
SNC 260
VCA 87
RtTg 258
VLL 128
SC 286
IC 207
10N 181
RtTg 257
IC 143
Sp5I 120
Sp

IO 236
3N 213
LPB 136
RMC 243
IO 237
VLL 288
LRt 283
RtTg 227
Amb 149
7n 275
LRt 170
DC 336
SC 269
IC 265
VCA 84
Sp5C 145
RtTg 195
Pn 253
7N 150
SNC 158
SNC 302
Pn 196
IC 254
VCA 350
Pn 250
7n 254
IC 183
VLL 292
Pn 255
5N 152
Pn 187
SNR 128
LRt 278
Sp5C 141
IC 264
Sp5C 154
10N 212
7n 187
Sp5I 110
IO 226
SNR 285
7n 245
IC 179
7n 164
DC 98
RMC 265
10N 218
SNC 147
DC 311
DC 306
Pn 171
LC 258
Sp5C 292
SC 138
Pn 277
SNC 282
IC 260
RtTg 239
IC 165
SNR 273
SNC 151
SNR 127
IC 277
5N 147
VCP 333
PBG 127
3N 211
SNC 261
10N 217
DC 324
SNC 269
Pn 189
7N 153
VCP 314
RMC 201
SNR 166
IC 175
RtTg 237
SC 160
Pn 260
SC 156
AP 193
RtTg 197
Sp5C 296
8n 310
SC 150
7N 173
SC 229
7N 160
LVe 136
12N 198
VCA 334
7N 283
IC 234
6N 195
SC 280
SNR 318
7n 284
Sp5O 119
SNC 284
6N 192
Cu 160
Tz 203
Pr5DM 310
RMC 193
Sp5I 105
SNR 269
VCA 103
VCA 86
IC 307
SNR 266
IC 172
VLL 289
Sp5C 114
SC 219
7N 290
7N 169
SNC 141
7N 144
RMC 242
SNR 286
Tz 192
IC 174
SNR 292
Pn 234
Pr5DM 115
SNC 155
Sp5I 306
VCA 325
SC 153
3N 232
VCA

8n 107
12N 205
RtTg 235
SC 250
SNR 169
Tz 242
RtTg 216
7n 249
12N 195
RMC 249
IC 167
SC 220
7n 227
Sp5I 307
VCP 96
RMC 265
10N 212
Sp5O 111
DC 325
DC 285
VCP 339
VLL 289
8n 306
RtTg 232
SC 162
4N 207
SNC 266
3N 225
IO 234
10N 203
7N 281
4N 212
3N 226
VLL 131
Sp5I 310
Sp5C 112
SNR 160
LC 261
SC 284
Sp5I 127
12N 216
7N 276
SC 294
SNR 321
7N 261
SC 282
Pr5DM 314
VLL 304
DC 296
6N 229
10N 220
SC 177
SNR 180
Pn 177
Pn 176
SC 167
VCA 330
SuVe 145
IO 201
IC 295
Sp5O 314
PBG 319
DC 89
3N 214
AP 193
SC 265
IC 267
SC 158
IC 166
RtTg 198
Sp5C 123
7n 259
DC 112
IO 228
12N 206
DC 291
DC 307
Sp5C 296
IC 152
Pr5DM 307
IC 192
SC 274
Tz 246
VLL 143
VCP 313
VCP 316
MVePC 170
SC 185
DC 319
SNC 281
SC 176
PBG 324
SC 281
IC 258
Sp5I 128
RMC 272
Sp5I 296
DC 108
Sp5C 147
LPB 137
AP 204
Pr5DM 120
Pn 236
SC 267
SNR 271
VLL 152
Pn 201
IC 255
SC 252
IC 236
SC 300
DC 292
IC 217
DC 297
SC 149
7n 151
IC 129
RtTg 243
MVeMC 167
Sp5C 122
7n 183
Sp5C 136
VCA 334
Pn 166
8n 115
7n 177
SNC 302
Amb 275
SNR 137
Pr5DM 312
7n

RMC 186
SNC 294
SNR 148
AP 203
SC 151
SNC 150
7n 167
3N 232
SC 149
IC 130
Sp5C 155
DC 129
SNR 164
Pr5VL 305
SC 154
IC 160
RtTg 224
7n 294
IC 151
SC 297
RtTg 211
VLL 138
Sol 157
RMC 275
DC 99
5N 283
IO 231
LRt 279
DC 131
7n 227
7n 277
IC 289
10N 208
Sp5I 312
IC 159
IC 243
VCA 97
7n 292
VLL 298
7n 175
RMC 203
IC 208
RMC 269
SC 186
8n 310
VLL 139
Pn 268
SC 152
DC 123
8n 122
8n 125
SC 252
SC 300
SNR 167
4N 228
10N 182
SNR 267
3N 230
IC 279
RtTg 181
3N 216
SNC 154
SNR 169
10N 204
VCA 96
LVe 138
RtTg 239
VCP 318
VLL 149
Tz 187
SNC 306
VCP 333
PBG 125
10N 178
DC 119
8n 116
Pn 178
Sp5I 310
DC 134
VCP 331
Sp5C 114
8n 320
SNC 145
Sp5C 134
7n 265
5N 285
Pn 194
7N 273
SNR 286
VCA 331
DC 285
Sp5I 288
SNR 323
LRt 160
Pr5VL 121
8n 105
7n 297
RtTg 179
VLL 130
SNR 275
5N 137
IC 249
IC 258
7n 233
Sp5I 309
SNC 167
7N 167
SNR 301
SNR 265
4N 205
IO 240
Pn 181
PBG 130
SpVe 160
7n 185
7n 243
LVe 140
Tz 230
12N 213
DC 334
12N 207
Tz 193
Pr5DM 315
SNR 324
IC 188
RMC 188
Tz 205
Sp5O 312
SC 191
VCA 95
5N 275
DC 

KeyboardInterrupt: 

In [179]:
merged_annotations_table = DataFrame(annotations.values())

In [180]:
merged_annotations_table

class  creator  \
61417973919587   contour  yuncong   
165498910605087  contour  yuncong   
110473719026558  contour  yuncong   
102790288330653  contour  yuncong   
108860727905611  contour  yuncong   
131633584750329  contour  yuncong   
217866353503758  contour  yuncong   
146476015747094  contour  yuncong   
126673529461145  contour  yuncong   
65942681262602   contour  yuncong   
92010441865970   contour  yuncong   
193478745432178  contour  yuncong   
19224556955380   contour  yuncong   
139228538863710  contour  yuncong   
257545148886987  contour  yuncong   
106159580668830  contour  yuncong   
191227155178395  contour  yuncong   
82935703639810   contour  yuncong   
101105623500811  contour  yuncong   
71804313132620   contour  yuncong   
137746592275401  contour  yuncong   
22145578028625   contour  yuncong   
225036892786054  contour  yuncong   
172039536449513  contour  yuncong   
190012648470873  contour  yuncong   
118078330761052  contour  yuncong   
279234224597201  contour  yuncong   
136849910734993  contour  yuncong   
155600714878127  contour  yuncong   
118141688879573  contour  yuncong   
...                  ...      ...   
56675330531695   contour  yuncong   
171678345729631  contour  yuncong   
186241270864853  contour  yuncong   
228564174641203  contour  yuncong   
175689311675128  contour  yuncong   
32622169502262   contour  yuncong   
1574135016703    contour  yuncong   
177794470581010  contour  yuncong   
243845345800769  contour  yuncong   
201873184737238  contour  yuncong   
25170032822165   contour  yuncong   
249688371806136  contour  yuncong   
72892179232617   contour  yuncong   
35369942739671   contour  yuncong   
208396518302891  contour  yuncong   
108604012128914  contour  yuncong   
267157701410975  contour  yuncong   
278317122053111  contour  yuncong   
121121780988994  contour  yuncong   
40087874423371   contour  yuncong   
679030166790     contour  yuncong   
183524020131991  contour  yuncong   
41974728783487   contour  yuncong   
258190930164209  contour  yuncong   
115137821918288  contour  yuncong   
267094528604537  contour  yuncong   
113458660685089  contour  yuncong   
251517374402717  contour  yuncong   
140476437520067  contour  yuncong   
211443647724471  contour  yuncong   

                                                             edits  \
61417973919587   [{u'username': u'yuncong', u'timestamp': u'041...   
165498910605087  [{u'username': u'yuncong', u'timestamp': u'041...   
110473719026558  [{u'username': u'yuncong', u'timestamp': u'041...   
102790288330653  [{u'username': u'yuncong', u'timestamp': u'041...   
108860727905611  [{u'username': u'yuncong', u'timestamp': u'041...   
131633584750329  [{u'username': u'yuncong', u'timestamp': u'041...   
217866353503758  [{u'username': u'yuncong', u'timestamp': u'041...   
146476015747094  [{u'username': u'yuncong', u'timestamp': u'041...   
126673529461145  [{u'username': u'yuncong', u'timestamp': u'041...   
65942681262602   [{u'username': u'yuncong', u'timestamp': u'041...   
92010441865970   [{u'username': u'yuncong', u'timestamp': u'041...   
193478745432178  [{u'username': u'yuncong', u'timestamp': u'041...   
19224556955380   [{u'username': u'yuncong', u'timestamp': u'041...   
139228538863710  [{u'username': u'yuncong', u'timestamp': u'041...   
257545148886987  [{u'username': u'yuncong', u'timestamp': u'041...   
106159580668830  [{u'username': u'yuncong', u'timestamp': u'041...   
191227155178395  [{u'username': u'yuncong', u'timestamp': u'041...   
82935703639810   [{u'username': u'yuncong', u'timestamp': u'041...   
101105623500811  [{u'username': u'yuncong', u'timestamp': u'041...   
71804313132620   [{u'username': u'yuncong', u'timestamp': u'041...   
137746592275401  [{u'username': u'yuncong', u'timestamp': u'041...   
22145578028625   [{u'username': u'yuncong', u'timestamp': u'041...   
225036892786054  [{u'username': u'yuncong', u'timestamp': u'041...   
172039536449513  [{u'username': u'yuncong', 

In [ ]:
fp = DataManager.get_annotation_filepath(stack=stack, by_human=True, suffix='contours', timestamp='now')
save_hdf_v2(merged_annotations_table, fp)
upload_to_s3(fp)

In [34]:
contours_df, timestamp = DataManager.load_annotation_v4(stack=stack, by_human=True, timestamp='latest', 
                                                        suffix='contours', return_timestamp=True)

aws s3 cp --recursive "s3://mousebrainatlas-data/CSHL_labelings_v3/CHATM3" "/home/yuncong/CSHL_labelings_v3/CHATM3" --exclude "*" --include "*contours*"
0
latest timestamp:  04172018132221


In [35]:
for cid in contours_df.index:
    contours_df.at[cid, 'creator'] = 'lauren'
    
    edits = contours_df.loc[cid]['edits']
    new_edits = []
    for edit in edits:
        new_edit = edit.copy()
        new_edit['username'] = 'lauren'
        new_edits.append(new_edit)
        
    contours_df.at[cid, 'edits'] = new_edits

In [36]:
contours_df

class creator  \
61417973919587   contour  lauren   
165498910605087  contour  lauren   
110473719026558  contour  lauren   
102790288330653  contour  lauren   
108860727905611  contour  lauren   
131633584750329  contour  lauren   
217866353503758  contour  lauren   
146476015747094  contour  lauren   
126673529461145  contour  lauren   
65942681262602   contour  lauren   
92010441865970   contour  lauren   
193478745432178  contour  lauren   
19224556955380   contour  lauren   
139228538863710  contour  lauren   
257545148886987  contour  lauren   
106159580668830  contour  lauren   
191227155178395  contour  lauren   
82935703639810   contour  lauren   
101105623500811  contour  lauren   
71804313132620   contour  lauren   
137746592275401  contour  lauren   
22145578028625   contour  lauren   
225036892786054  contour  lauren   
172039536449513  contour  lauren   
190012648470873  contour  lauren   
118078330761052  contour  lauren   
279234224597201  contour  lauren   
136849910734993  contour  lauren   
155600714878127  contour  lauren   
118141688879573  contour  lauren   
...                  ...     ...   
56675330531695   contour  lauren   
171678345729631  contour  lauren   
186241270864853  contour  lauren   
228564174641203  contour  lauren   
175689311675128  contour  lauren   
32622169502262   contour  lauren   
1574135016703    contour  lauren   
177794470581010  contour  lauren   
243845345800769  contour  lauren   
201873184737238  contour  lauren   
25170032822165   contour  lauren   
249688371806136  contour  lauren   
72892179232617   contour  lauren   
35369942739671   contour  lauren   
208396518302891  contour  lauren   
108604012128914  contour  lauren   
267157701410975  contour  lauren   
278317122053111  contour  lauren   
121121780988994  contour  lauren   
40087874423371   contour  lauren   
679030166790     contour  lauren   
183524020131991  contour  lauren   
41974728783487   contour  lauren   
258190930164209  contour  lauren   
115137821918288  contour  lauren   
267094528604537  contour  lauren   
113458660685089  contour  lauren   
251517374402717  contour  lauren   
140476437520067  contour  lauren   
211443647724471  contour  lauren   

                                                             edits  \
61417973919587   [{u'username': u'lauren', u'timestamp': u'0416...   
165498910605087  [{u'username': u'lauren', u'timestamp': u'0416...   
110473719026558  [{u'username': u'lauren', u'timestamp': u'0416...   
102790288330653  [{u'username': u'lauren', u'timestamp': u'0416...   
108860727905611  [{u'username': u'lauren', u'timestamp': u'0416...   
131633584750329  [{u'username': u'lauren', u'timestamp': u'0416...   
217866353503758  [{u'username': u'lauren', u'timestamp': u'0416...   
146476015747094  [{u'username': u'lauren', u'timestamp': u'0416...   
126673529461145  [{u'username': u'lauren', u'timestamp': u'0416...   
65942681262602   [{u'username': u'lauren', u'timestamp': u'0416...   
92010441865970   [{u'username': u'lauren', u'timestamp': u'0416...   
193478745432178  [{u'username': u'lauren', u'timestamp': u'0416...   
19224556955380   [{u'username': u'lauren', u'timestamp': u'0416...   
139228538863710  [{u'username': u'lauren', u'timestamp': u'0416...   
257545148886987  [{u'username': u'lauren', u'timestamp': u'0416...   
106159580668830  [{u'username': u'lauren', u'timestamp': u'0416...   
191227155178395  [{u'username': u'lauren', u'timestamp': u'0416...   
82935703639810   [{u'username': u'lauren', u'timestamp': u'0416...   
101105623500811  [{u'username': u'lauren', u'timestamp': u'0416...   
71804313132620   [{u'username': u'lauren', u'timestamp': u'0416...   
137746592275401  [{u'username': u'lauren', u'timestamp': u'0416...   
22145578028625   [{u'username': u'lauren', u'timestamp': u'0416...   
225036892786054  [{u'username': u'lauren', u'timestamp': u'0416...   
172039536449513  [{u'username': u'lauren', u'timestamp': u'0416...   
190012648470873  [{u'username': u'la

In [37]:
fp = DataManager.get_annotation_filepath(stack=stack, by_human=True, suffix='contours', timestamp='now')
save_hdf_v2(contours_df, fp)
upload_to_s3(fp)

aws s3 cp "/home/yuncong/CSHL_labelings_v3/CHATM3/CHATM3_annotation_contours_04252018112445.hdf" "s3://mousebrainatlas-data/CSHL_labelings_v3/CHATM3/CHATM3_annotation_contours_04252018112445.hdf"
0
